### ISSUE TITLE
Consider using Linux 2 AMI instead of Linux AMI

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/terraform-aws-ecs#14]
A part of the changes for https://github.com/philips-software/terraform-aws-ecs/pull/13 have to do with using Amazon Linux 2 AMIs instead of Amazon Linux AMIs.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/al2ami-get-latest.html
vs
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI_launch_latest.html

Switch to Amazon Linux 2 AMIs.

**Comment by npalm** [comment]
Create a PR https://github.com/philips-software/terraform-aws-ecs/pull/new/feature/upgrade-azn-linux2-and-default-latest

**Comment by JeroenKnoops** [comment]
@npalm You're putting a link to **create** a pull request instead of to an **existing** pull request.. Is it already done?

**Comment by npalm** [comment]
@JeroenKnoops is still some work in progress. Will check the changes, as soon ready a PR will be created.

**Comment by JeroenKnoops** [comment]
Closed by #15
